const GET_MOVIES_REQUESTM = "GET_MOVIES_REQUESTM";
const GET_MOVIES_SUCCESSM = "GET_MOVIES_SUCCESSM";
const GET_MOVIES_FAILUREM = "GET_MOVIES_FAILUREM";
export {GET_MOVIES_REQUESTM,
  GET_MOVIES_SUCCESSM,
  GET_MOVIES_FAILUREM}